"""One-off driver: create store "Ashok 9 June", reveal dev token, seed products,
generate carrier env. Headed (the Playwright scripts launch headless:false)."""
from __future__ import annotations

import sys
import traceback

from pipeline.new_carrier_onboarding import (
    create_store_and_install_app,
    create_dev_app_and_reveal_token,
)
from pipeline.shopify_product_seed import create_seed_products
from pipeline.new_carrier_validation import (
    NewCarrierValidationRun,
    ShopifyProductRef,
    build_carrier_env_content,
    write_carrier_env_file,
    save_new_carrier_run,
)

STORE_INPUT = "Ashok 9 June"
CARRIER = "ashok-9-june"


def log(msg: str) -> None:
    print(f"\n=== {msg} ===", flush=True)


def main() -> int:
    # 1) Create store + install QA app
    log("STEP 1/4: Create store + install app (headed)")
    onboard = create_store_and_install_app(store_name=STORE_INPUT)
    slug = onboard.store_name
    print(f"store_created={onboard.store_created} app_installed={onboard.app_installed}", flush=True)
    print(f"realized_slug={slug}", flush=True)
    print(f"shopify_url={onboard.shopify_url}", flush=True)
    print(f"app_url={onboard.app_url}", flush=True)
    print(f"duration={onboard.duration_seconds:.0f}s", flush=True)
    if not slug:
        print("ABORT: no realized store slug", flush=True)
        return 2

    # 2) Create dev app + reveal admin token
    log("STEP 2/4: Create dev app + reveal token (headed)")
    tok = create_dev_app_and_reveal_token(store_name=slug)
    print(f"app_id={tok.app_id} app_installed={tok.app_installed} token_revealed={tok.token_revealed}", flush=True)
    print(f"granted_scopes={len(tok.granted_admin_scopes)} missing={list(tok.missing_admin_scopes)}", flush=True)
    token = tok.admin_token
    if not token:
        print("WARN: no admin token revealed; env will have empty SHOPIFY_ACCESS_TOKEN", flush=True)

    # 3) Seed products
    product_groups: dict[str, list[ShopifyProductRef]] = {}
    if token:
        log("STEP 3/4: Create seed products")
        try:
            seeded = create_seed_products(
                carrier_code=CARRIER,
                store_name=slug,
                shopify_access_token=token,
            )
            for group, items in seeded.items():
                product_groups[group] = [
                    ShopifyProductRef(product_id=r.product_id, variant_id=r.variant_id)
                    for r in items
                ]
                print(f"{group}: {[(r.product_id, r.variant_id) for r in items]}", flush=True)
        except Exception as exc:  # noqa: BLE001
            print(f"PRODUCT SEED FAILED: {exc}", flush=True)
            traceback.print_exc()
    else:
        log("STEP 3/4: skipped (no token)")

    # 4) Build + write env
    log("STEP 4/4: Build carrier env")
    run = NewCarrierValidationRun(
        carrier_code=CARRIER,
        store_name=slug,
        store_created=onboard.store_created,
        app_installed=onboard.app_installed,
        app_url=onboard.app_url,
        shopify_url=onboard.shopify_url,
        shopify_access_token=token,
        product_groups=product_groups,
        registration_done=False,
        registration_notes="Carrier registration is a separate manual step; env generated by driver.",
        notes="Created via tmp driver for store 'Ashok 9 June'.",
    )
    env_text = build_carrier_env_content(run)
    env_path = write_carrier_env_file(run)
    run_path = save_new_carrier_run(run)

    log("CARRIER ENV CONTENT")
    print(env_text, flush=True)
    log("PATHS")
    print(f"env_file={env_path}", flush=True)
    print(f"run_record={run_path}", flush=True)
    return 0


if __name__ == "__main__":
    sys.exit(main())
